apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
  labels:
    osp/net: data-centre
    service: ovn-controller
  name: datacentre
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "datacentre",
      "type": "bridge",
      "bridge": "ospbr",
      "ipam": {}
    }
