apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: openstack
spec:
  secret: osp-secret
  storageClass: local-storage
  tls:
    ingress:
      enabled: true
      ca:
        customIssuer: rootca-ingress-custom
    podLevel:
      enabled: true
      internal:
        ca:
          customIssuer: rootca-internal-custom
